### ISSUE TITLE
pro pro pro pro pro pro pro pro pro pro pro pro pro pro 

### ISSUE THREAD

**Issue by Assassin-1234** [Nuggies-bot/Nuggies#198]
@pro-gamer007 CHECK YOUR FUCKIN DMS ON DISCORD BRUH

**Comment by Assassin-1234** [comment]
yeah this was the only way sorry

**Comment by pro-gamer007** [comment]
Bruh moment. I told you I'm on a break from discord 😐.

**Comment by pro-gamer007** [comment]
Just tell me here :trollface:

**Comment by Assassin-1234** [comment]
yeah then gimme the env file RN

**Comment by Assassin-1234** [comment]
![image](https://user-images.githubusercontent.com/68866924/115991057-219d1000-a5e4-11eb-81e9-c28d94dba131.png)
legitmate also wants you to come back

**Comment by Assassin-1234** [comment]
@pro-gamer007

**Comment by pro-gamer007** [comment]
```
cd Nuggies
sudo nano .env
```

**Comment by pro-gamer007** [comment]
And ill come back

**Comment by pro-gamer007** [comment]
After my break :trollface:

**Comment by Assassin-1234** [comment]
and how do you start the process with env, last time me and IYR failed to do it last time TwT

**Comment by Assassin-1234** [comment]
also stop being on github dumbass go and take your break

**Comment by Assassin-1234** [comment]
> After my break :trollface:

when

**Comment by pro-gamer007** [comment]
> and how do you start the process with env, last time me and IYR failed to do it last time TwT

Wdym, its normal

**Comment by pro-gamer007** [comment]
> also stop being on github dumbass go and take your break

its a break from discord not GitHub. I'm allways available for Nuggies just cant be on discord ig

**Comment by Assassin-1234** [comment]
can you write the functions for economy, just the balance and deposit for now

**Comment by Assassin-1234** [comment]
I lost them when my dad reset pc

**Comment by Assassin-1234** [comment]
legitmate stop reacting

**Comment by Assassin-1234** [comment]
we need a better way to communicate 🧠

**Comment by Assassin-1234** [comment]
how do you copy from nano btw

**Comment by Assassin-1234** [comment]
ctrl + c no work

**Comment by pro-gamer007** [comment]
Ctrl + shift + c

**Comment by pro-gamer007** [comment]
> can you write the functions for economy, just the balance and deposit for now

Idk just tell me and maybe i can try doing them later

**Comment by pro-gamer007** [comment]
> we need a better way to communicate 🧠 

Nah fam github :ye:

**Comment by pro-gamer007** [comment]
Also if you ever need some help from vps side of things or something, mention me. I get notifs everytime i get mentioned so yuh

**Comment by Assassin-1234** [comment]
okay lets keep this issue open then ig

**Comment by Assassin-1234** [comment]
my last words for today.

**babytard is retarded** 🥱

**Comment by pro-gamer007** [comment]
Lmfao

**Comment by pro-gamer007** [comment]
@Assassin-1234 wait a min, didnt i tell you i was gone for like a week?

**Comment by pro-gamer007** [comment]
Ayo is legitmate part of dev team now?

**Comment by Assassin-1234** [comment]
yes

**Comment by pro-gamer007** [comment]
Very good decision

**Comment by pro-gamer007** [comment]
ayo ass, could you tell bogusmosquito to check out [this](https://github.com/pro-gamer007/simple-youtube-downloader/releases/tag/mac.windows.linux.2.0.0)

**Comment by pro-gamer007** [comment]
doesnt have to be ass could be anyone 🥺

**Comment by Assassin-1234** [comment]
done

**Comment by pro-gamer007** [comment]
Ty g

**Comment by BogusMosquito77** [comment]
pro, it's epic

**Comment by pro-gamer007** [comment]
Did you get a chance to try it out on linux? 😳

**Comment by pro-gamer007** [comment]
I had made the original exe on my laptop and then i made the mac dmg on my dads mac and then i made the linux app image and deb on the mac too just never got to test the app image and deb cuz i dont have any vms on the mac :/

**Comment by Justmetaboy-Cord** [comment]
Lol using r slurs are so funny. - 
Sincerely a bad bitch
To Assassin
Side note DONT SAY THE R SLUR I WILL EXPOSE U

**Comment by Justmetaboy-Cord** [comment]
Just met a boy, just met a boy when
He could come inside of my play pen
'Cause he look like a superstar in the makin'
So I think that I'm going in for the takin'
Hear through the grapevine that he cakin'
We could shoot a movie, he could the tapin'
Boom boom pow, this thing be shakin'
I ain't even tryin' to find out who he datin'
'Cause I know that he got a wife at home
But I need just one night alone
If you keep playin' them g-g-games
I'ma runaway (Ay), I'ma runaway (Ay, ay)
I-I-I wanna give you one last option
I-I-I wanna give you one last chance
If-if you're looking for the main attraction
Just hold on tight and let me do my dance
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
Just met a boy, just met a boy when
He could become my little problem
'Cause he look like he modellin' clothes in Dublin
So I think that he gettin' that green, a goblin
Heard through the grapevine that he hang low
We could shoot a movie, could bang like Rambo
Boom boom pow, this thing so bingo
Wondering if he can understand my lingo
'Cause I know, he got a wife at home
But I need just one night alone
If he keep playin' them g-g-games
I'ma runaway (Ay), I'ma runaway (Ay, ay)
I-I-I wanna give you one last option
I-I-I wanna give you one last chance
If-if you're looking for the main attraction
Just hold on tight and let me do my dance
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
Boy I'm in this club slow-mo, don't mind if I do
And I can tell you're feelin' me from the jump, I wanna ride too
You got that hot shit, boy ya blessed, let me feel up on yo' chest
Flex it, you da man, you da man, one hundred grand
The same old game blow, yes, I play it very well
Come baby, lay it down, let me stay down
Let me show you how I run tings in my playground
Come and get this va va voom voom (woo woo)
I-I-I wanna give you one last option
I-I-I wanna give you one last chance
If-if you're looking for the main attraction
Just hold on tight and let me do my dance
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
If you want it, I'm gonna be va va voom voom
If you got it, you got it, you got that boom boom
FROM THE QUEEN OF RAP NICKI MINAJ

**Comment by Justmetaboy-Cord** [comment]
I’m so bored

**Comment by Justmetaboy-Cord** [comment]
Say something

**Comment by Justmetaboy-Cord** [comment]
Love ur bot nuggies

**Comment by Justmetaboy-Cord** [comment]
SIKE

**Comment by Justmetaboy-Cord** [comment]
SIKKEYY MIKEYYY

**Comment by Justmetaboy-Cord** [comment]
Do you guys want more NICKI MINAJ

**Comment by Justmetaboy-Cord** [comment]
I THINK YOU DO

**Comment by Justmetaboy-Cord** [comment]
Maybe some Olivia ordigo

**Comment by Justmetaboy-Cord** [comment]
Ye some deja vu

**Comment by Justmetaboy-Cord** [comment]
Car rides to Malibu
Strawberry ice cream
One spoon for two
And trading jackets
Laughing 'bout how small it looks on you
(Ha-ha-ha-ha, ha-ha-ha-ha, ha-ha-ha-ha)
Watching reruns of Glee
Being annoying
Singing in harmony
I bet she's bragging
To all her friends, saying you're so unique, hmm
So when you gonna tell her
That we did that too?
She thinks it's special
But it's all reused
That was our place, I found it first
I made the jokes you tell to her when she's with you
Do you get déjà vu when she's with you?
Do you get déjà vu? (Ah), hmm
Do you get déjà vu, huh?
Do you call her
Almost say my name?
'Cause let's be honest
We kinda do sound the same
Another actress
I hate to think that I was just your type
I'll bet that she knows Billy Joel
'Cause you played her Uptown Girl
You're singing it together
Now I bet you even tell her
How you love her
In between the chorus and the verse (ooh) (I love you)
So when you gonna tell her
That we did that too?
She thinks it's special
But it's all reused
That was the show we talked about
Played you the song she's singing now when she's with you
Do you get déjà vu when she's with you?
Do you get déjà vu? Oh
Do you get déjà vu?
Strawberry ice cream in Malibu
Don't act like we didn't do that shit too
You're trading jackets like we used to do
(Yeah, everything is all reused)
Play her piano, but she doesn't know (oh, oh)
That I was the one who taught you Billy Joel (oh)
A different girl now, but there's nothing new
(I know you get déjà vu)
I know you get déjà vu
I know you get déjà vu

**Comment by Justmetaboy-Cord** [comment]
Do you get deja vu? Assassin?

**Comment by Justmetaboy-Cord** [comment]
REEE

**Comment by Justmetaboy-Cord** [comment]
REEE











REEE






REE









REEEE

**Comment by Justmetaboy-Cord** [comment]
Can I spam?

**Comment by Justmetaboy-Cord** [comment]
I think I can

**Comment by Justmetaboy-Cord** [comment]
.

**Comment by Justmetaboy-Cord** [comment]
S

**Comment by Justmetaboy-Cord** [comment]
@Assassin-1234  poop

**Comment by Justmetaboy-Cord** [comment]
Read my messages @Assassin-1234

**Comment by Justmetaboy-Cord** [comment]
Don’t say your busy

**Comment by Justmetaboy-Cord** [comment]
Read my messages

**Comment by Justmetaboy-Cord** [comment]
It’s good

**Comment by Justmetaboy-Cord** [comment]
For your reading enhancement

**Comment by Justmetaboy-Cord** [comment]
Heyy

**Comment by pro-gamer007** [comment]
Bruh moment

**Comment by pro-gamer007** [comment]
I'm not gonnna bother deleting all these 🥱

**Comment by Assassin-1234** [comment]
> Lol using r slurs are so funny. -
> Sincerely a bad bitch
> To Assassin
> Side note DONT SAY THE R SLUR I WILL EXPOSE U

Retard

**Comment by Assassin-1234** [comment]
@Justmetaboy-Cord idgaf what you do lmao, please go fuck yourself

**Comment by Justmetaboy-Cord** [comment]
I already did

**Comment by Justmetaboy-Cord** [comment]
Reeee

**Comment by Justmetaboy-Cord** [comment]
Reeeee

**Comment by pro-gamer007** [comment]
Sus

**Comment by pro-gamer007** [comment]
:flushed: ![image](https://user-images.githubusercontent.com/66844505/116182076-5078ca80-a739-11eb-8f3d-120be5d3fb5b.png)

**Comment by Assassin-1234** [comment]
your break ends tomorrow @pro-gamer007

**Comment by pro-gamer007** [comment]
No

**Comment by pro-gamer007** [comment]
Hold on lemme get a screenshot of what i told someone

**Comment by pro-gamer007** [comment]
![image](https://user-images.githubusercontent.com/66844505/116355372-61980900-a817-11eb-93e4-db460eac0e7a.jpeg)

**Comment by Assassin-1234** [comment]
@pro-gamer007 come back your break is over ❗  ❗  ❗  ❗  ❗ ![image](https://user-images.githubusercontent.com/68866924/116454675-def66480-a87d-11eb-9975-83195617d509.png)

**Comment by pro-gamer007** [comment]
Stfu

**Comment by pro-gamer007** [comment]
Give me like 2 more days 😩 
I have 2-3 tests that i have and cant get no distractions

**Comment by pro-gamer007** [comment]
@Assassin-1234 idky but the api sometimes goes off... Should i host the api on our server instead?

**Comment by Assassin-1234** [comment]
sure thing ig

**Comment by Assassin-1234** [comment]
I dont think its the server tho, its most prolly cuz of errors

**Comment by pro-gamer007** [comment]
Nono its not the code

**Comment by pro-gamer007** [comment]
Because of the err

**Comment by pro-gamer007** [comment]
Wait hold up

**Comment by pro-gamer007** [comment]
Its not because of api errs, uptime robot says its up all the time but if i check the repl then its down...

**Comment by pro-gamer007** [comment]
Nvm today it actually did go down
![image](https://user-images.githubusercontent.com/66844505/116588971-cba8cf00-a939-11eb-9d59-2da1c8d6b239.jpeg)

**Comment by Assassin-1234** [comment]
@pro-gamer007 come back, we're working on something and we're kinda short on devs 😳

**Comment by pro-gamer007** [comment]
But i cant do shit until my bro would give back laptop 🙄

**Comment by Assassin-1234** [comment]
when will he?

**Comment by Assassin-1234** [comment]
just come on Ipad bro

**Comment by pro-gamer007** [comment]
what is it doe? Could you tell me through git?

**Comment by Assassin-1234** [comment]
RPG, we arent doing economy now, it'll be an RPG system.. we already started

**Comment by pro-gamer007** [comment]
I cant decide if thats a cool thing or if thats just a "what the fuck" moment

**Comment by pro-gamer007** [comment]
Explain me more about it

**Comment by Assassin-1234** [comment]
I cant give details here cuz spoilers so come discord dms

**Comment by Assassin-1234** [comment]
@pro-gamer007 can you add my id to the top.gg page? 833713876628406363

**Comment by pro-gamer007** [comment]
@Assassin-1234 cant

**Comment by pro-gamer007** [comment]
Ill come back today after school

**Comment by Assassin-1234** [comment]
school not over yet?

**Comment by pro-gamer007** [comment]
You were 10 min early
